newtonschool/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.newton_school_dashboard, name='school_dashboard'),
    path('newtonschool/about/', views.newton_school_about, name='school_about'),
    path('newtonschool/courses/', views.CoursesListView.as_view(), name='courses'),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls')),
    path('', include('newtonschool.urls')),
    path('users/', include('users.urls')),
    path('students/', include('students.urls')),
    path('payments/', include('payments.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.users_login, name='users_login'),
    path('logout/', views.log_out, name='logout'),
    path('registration/', views.choose_user, name='choose_user'),
    path('registration/student/', views.student_registration, name='student_reg'),
    path('registration/teacher/', views.teacher_registration, name='teacher_reg'),
    path('submitted/', views.thanks_submission, name='user_submit'),
    path('password_reset/', views.user_change_pass, name='user_change_pass'),
    path('datasets/', views.users_dataset, name='users_dataset'),
    path('user_detail_data/<int:ids>/', views.user_detail_data, name='user_detail_data'),
    path('edit/', views.user_profile_edit, name='user_profile_edit'),
]

newtonschool/models.py
from django.db import models


# Create your models here.
class School(models.Model):
    DATA_CHOICE = [('A', 'Good Institute'),
                   ('B', 'Average Institute'),
                   ('C', 'Very Poor Institute')
                   ]
    institute_name = models.CharField(max_length=44)
    established_year = models.IntegerField()
    owner_name = models.CharField(max_length=25)
    address = models.TextField(max_length=100)
    rating = models.CharField(max_length=5, choices=DATA_CHOICE)

teachers/models.py
from django.db import models
from .choices import COURSE_TYPE_CHOICES


class Courses(models.Model):
    course_name = models.CharField(max_length=255)
    standard = models.IntegerField()
    course_description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    course_type = models.CharField(max_length=10, choices=COURSE_TYPE_CHOICES)
    price = models.IntegerField()
    teacher = models.ForeignKey('users.SchoolUser', on_delete=models.CASCADE)

newtonschool/forms.py
from django import forms
from .models import School


class SchoolModelForm(forms.ModelForm):
    class Meta:
        model = School
        fields = ['established_year', 'rating', 'address', 'owner_name']
        error_messages = {
            'owner_name': {'required': "Please Enter Correct Name"}
        }

newtonschool/views.py
from django.shortcuts import render
from teachers.models import Courses
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.urls import reverse
from users.models import USER_CHOICE_VALUE_TEACHER, USER_CHOICE_VALUE_STUDENT


# Create your views here.
def newton_school_dashboard(request):
    return render(request, "newtonschool/dashboard.html", )


def newton_school_about(request):
    """Simple about view"""
    return render(request, "newtonschool/about.html")


class CoursesListView(ListView):
    model = Courses
    template_name = 'newtonschool/courses.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.user_type == USER_CHOICE_VALUE_TEACHER:
            self.object_list = super().get_queryset()
            context = super().get_context_data(**kwargs)
            return render(request, self.template_name, context)
        else:
            return HttpResponseRedirect(reverse('school_dashboard'))

newtonschool/templates/newtonschool/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Newton School | About</title>
    <link rel="shortcut icon" type="images" href="images/logo.jpg">

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'newtonschool/css/style.css' %}">

</head>

<body>

    <!-- header section starts  -->

    <header class="header">

      <a href="{% url 'school_dashboard' %}" class="logo"> <i class="fas fa-user-graduate"></i> Newton School </a>

        <div id="menu-btn" class="fas fa-bars"></div>

        <nav class="navbar">
            <ul>
                <li><a href="{% url 'school_dashboard' %}">HOME</a></li>
                <li><a href="about.html">ABOUT</a></li>
                <li><a href="gallery1.html">GALLERY</a></li>
                <li><a href="{% url 'student_reg' %}">STUDENT LOGIN</a></li>
                <li><a href="{% url 'teacher_reg' %}">TEACHER LOGIN</a></li>
            </ul>
        </nav>

    </header>

    <!-- header section ends -->

    <section class="heading">
        <h3>about us</h3>
        <p> <a href="{% url 'school_dashboard' %}">home >></a> about </p>
    </section>

    <!-- about section starts  -->

    <section class="about">

        <div class="image">
            <img src="images/about-img.png" alt="">
        </div>

        <div class="content">
            <h3>I will stay with you until you pass your exam.</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id ducimus at maiores repellat aut debitis aliquam esse, quisquam nobis laborum velit voluptate excepturi obcaecati dignissimos omnis. Fugiat hic quod nobis?</p>
            <a href="about us.html" class="btn">learn more</a>
        </div>

    </section>

    <!-- about section ends -->






















    <!-- footer section starts  -->

    <section class="footer">

        <div class="box-container">

           <div class="box">
                <h3>explore</h3>
                <a href="{% url 'school_dashboard' %}"> <i class="fas fa-arrow-right"></i> HOME </a>
                <a href="{% url 'school_about' %}"> <i class="fas fa-arrow-right"></i> ABOUT </a>
                <a href="course-1.html"> <i class="fas fa-arrow-right"></i> GALLERY </a>
                <a href="{% url 'student_reg' %}"> <i class="fas fa-arrow-right"></i> STUDENT LOGIN </a>
                <a href="{% url 'teacher_reg' %}"> <i class="fas fa-arrow-right"></i> TEACHER LOGIN </a>
            </div>

            <div class="box">
                <h3>Follow US</h3>
                <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
                <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
                <a href="#"> <i class="fab fa-linkedin"></i> linkedin </a>
                <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
                <a href="https://www.youtube.com/channel/UCXxTe5lB_fjn1H5azGBgWDw"> <i class="fab fa-youtube"></i> youtube </a>
                <a href="#"> <i class="fab fa-github"></i> github </a>
            </div>

        </div>

        <div class="credit"> created by <span>Dhaval Gojiya</span> | all rights reserved! </div>

    </section>

    <!-- footer section ends -->

    <!-- custom js file link  -->
    <script src="{% static 'newtonschool/js/school.js' %}"></script>


</body>

</html>

newtonschool/templates/newtonschool/courses.html
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--      BOOTSTRAP CSS LINK....-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!--      CUSTOM CSS LINK....-->
    <link rel="stylesheet" href="{% static 'newtonschool/css/courses.css' %}">
    <title>NewtonSchool Courses</title>
</head>
<body>
<div class="wrapper">
    {% for course in courses_list %}
    {% if course.course_name %}
    <div class="table basic">
        <div class="price-section">
            <div class="price-area">
                <div class="inner-area">
                       <span class="text">
                         &#8377;
                       </span>
                    <span class="price">{{course.price}}</span>
                </div>
            </div>
        </div>
        <div class="package-name">
            <h1 class="course-heading">{{course.course_name}}</h1>
        </div>
        <div class="features" style="text-align:center;">
            <span>{{ course.course_description }}</span>
        </div>
        <div class="btn-div-box">
            {% if course.course_type == 'paid' %}
            <a href="{% url 'student_course_enroll' pk=course.id %}" class="btn btn-info">Purchase</a>
            {% else %}
            <a href="{% url 'student_course_enroll' pk=course.id %}" class="btn btn-success">Enroll</a>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
</body>
</html>

newtonschool/templates/newtonschool/dashboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Newton School</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- bootstrap css file link  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- custom newtonschool css file link  -->
    <link rel="stylesheet" href="{% static 'newtonschool/css/style.css' %}">
    {% block users_css %}
    {% endblock %}
</head>

<body>

<!-- header section starts  -->

<header class="header">

    <a href="{% url 'school_dashboard' %}" class="logo"> <i class="fas fa-user-graduate"></i></a> <a
        href="{% url 'school_dashboard' %}" class="logo">Newton School</a>

    <div id="menu-btn" class="fas fa-bars"></div>
    <nav class="navbar">
        <ul>
            <li><a href="{% url 'school_dashboard' %}">HOME</a></li>
            <li><a href="{% url 'school_about' %}">ABOUT</a></li>
            <li><a href="{% url 'courses' %}">COURSES</a></li>
            {% if not request.user.is_authenticated %}
            <li><a href="{% url 'users_login' %}">USER LOGIN</a></li>
            {% endif %}
        </ul>
        {% if request.user.is_authenticated %}
        <!--        bootstrap dropdown burger-->
        <div class="dropdown navbar-nav">
            <img class="login-icon" src="{{ request.user.user_icon.url }}" alt="User Profile Image"/>
            <a href="#" class="user-pf">{{ request.user.get_full_name }}</a>
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
            >
            </button>
            <ul class="dropdown-menu p-0" id="dropdown-ul">
                <li><a class="dropdown-item" href="{% url 'user_profile_edit' %}">My Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
        {% endif %}
        <!--        bootstrap dropdown burger End-->
    </nav>

</header>

<!-- header section ends -->


<!-- home section starts  -->

<section class="home">

    <div class="image">
        <img src="{% static 'newtonschool/images/home-img.png'%}" alt="">
    </div>

    <div class="content">
        <h3>come and achieve your goal</h3>
        <p>we providing the best education among the all other schools.</p>
        <a href="map.html" class="btn">View school in map</a>
    </div>

</section>

<!-- home section ends -->

<!-- categories section starts  -->

<section class="category">

    <a href="#" class="box">
        <img src="{% static 'newtonschool/images/category-1.png'%}" alt="">
        <h3>computer science</h3>
    </a>

    <a href="#" class="box">
        <img src="{% static 'newtonschool/images/category-2.png'%}" alt="">
        <h3>biology & life</h3>
    </a>

    <a href="#" class="box">
        <img src="{% static 'newtonschool/images/category-3.png'%}" alt="">
        <h3>business analysis</h3>
    </a>

    <a href="#" class="box">
        <img src="{% static 'newtonschool/images/category-4.png'%}" alt="">
        <h3>social science</h3>
    </a>

    <a href="#" class="box">
        <img src="{% static 'newtonschool/images/category-5.png'%}" alt="">
        <h3>data analysis</h3>
    </a>

</section>

<!-- categories section ends -->


<!-- footer section starts  -->

<section class="footer">

    <div class="box-container">

        <div class="box">
            <h3>explore</h3>
            <a href="{% url 'school_dashboard' %}"> <i class="fas fa-arrow-right"></i> HOME </a>
            <a href="{% url 'school_about' %}"> <i class="fas fa-arrow-right"></i> ABOUT </a>
            <a href="course-1.html"> <i class="fas fa-arrow-right"></i> GALLERY </a>
            <a href="{% url 'student_reg' %}"> <i class="fas fa-arrow-right"></i> STUDENT LOGIN </a>
            <a href="{% url 'teacher_reg' %}"> <i class="fas fa-arrow-right"></i> TEACHER LOGIN </a>
        </div>

        <div class="box">
            <h3>Follow US</h3>
            <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
            <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
            <a href="#"> <i class="fab fa-linkedin"></i> linkedin </a>
            <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
            <a href="https://www.youtube.com/channel/UCXxTe5lB_fjn1H5azGBgWDw"> <i class="fab fa-youtube"></i> youtube
            </a>
            <a href="#"> <i class="fab fa-github"></i> github </a>
        </div>

    </div>

    <div class="credit"> created by <span>Dhaval Gojiya</span> | all rights reserved!</div>

</section>

<!-- footer section ends -->


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- bootstrap js file link  -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- custom js file link  -->
<script src="{% static 'newtonschool/js/school.js' %}"></script>

</body>

</html>