school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls')),
    path('', include('newtonschool.urls')),
    path('users/', include('users.urls')),
    path('students/', include('students.urls')),
    path('payments/', include('payments.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.users_login, name='users_login'),
    path('logout/', views.log_out, name='logout'),
    path('registration/', views.choose_user, name='choose_user'),
    path('registration/student/', views.student_registration, name='student_reg'),
    path('registration/teacher/', views.teacher_registration, name='teacher_reg'),
    path('submitted/', views.thanks_submission, name='user_submit'),
    path('password_reset/', views.user_change_pass, name='user_change_pass'),
    path('datasets/', views.users_dataset, name='users_dataset'),
    path('user_detail_data/<int:ids>/', views.user_detail_data, name='user_detail_data'),
    path('edit/', views.user_profile_edit, name='user_profile_edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

USER_CHOICE_VALUE_STUDENT = 'S'
USER_CHOICE_VALUE_TEACHER = 'T'


# Create your models here.
class SchoolUser(AbstractUser):
    USER_CHOICE = [(USER_CHOICE_VALUE_TEACHER, 'Teacher'),
                   (USER_CHOICE_VALUE_STUDENT, 'Student'),
                   ]
    birthdate = models.DateField(null=True, blank=True)
    phone = models.IntegerField(null=True, blank=True)
    standard = models.IntegerField(null=True, blank=True)
    subject = models.CharField(max_length=30, blank=True)
    email = models.EmailField(unique=True)
    local_address = models.TextField(max_length=200, blank=True)
    permanent_address = models.TextField(max_length=200, blank=True)
    user_type = models.CharField(max_length=10, choices=USER_CHOICE)
    terms_conditions = models.BooleanField(default=False)
    user_icon = models.ImageField(upload_to='images/profile-icon', blank=True,
                                  default='images/no-profile-icon/default.png')

    REQUIRED_FIELDS = ['local_address', 'email']


class UserAddresses(models.Model):
    street1 = models.CharField(max_length=400)
    street2 = models.CharField(max_length=400)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    pincode = models.IntegerField()
    is_default = models.BooleanField(default=True)
    user = models.ForeignKey('SchoolUser', on_delete=models.CASCADE)

    class Meta:
        db_table = 'users_addresses'

users/forms.py
from django import forms
from django.forms import ValidationError
from .models import SchoolUser
from django.contrib.auth.forms import PasswordChangeForm
from re import search as reg
from django.contrib.auth import authenticate


class SchoolUserModelForm(forms.ModelForm):
    confirm_password = forms.CharField(required=False, label='Confirm Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}), error_messages={'required': "please confirm your password."})

    class Meta:
        model = SchoolUser
        fields = ['first_name', 'last_name', 'username', 'user_icon', 'email', 'birthdate', 'phone', 'standard',
                  'subject', 'password', 'terms_conditions']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'user_icon': forms.FileInput(attrs={}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'birthdate': forms.DateInput(attrs={}),
            'phone': forms.NumberInput(attrs={}),
            'standard': forms.NumberInput(attrs={'class': 'form-control'}),
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'local_address': forms.Textarea(attrs={'cols': 30, 'rows': 2}),
            'permanent_address': forms.Textarea(attrs={'cols': 30, 'rows': 2}),
            'terms_conditions': forms.CheckboxInput(attrs={'class': 'form-check-input'}),

        }
        error_messages = {
            'username': {
                'required': "your username is necessary.",
            },
            'password': {
                'required': "please enter the password.",
            },
            'email': {
                'required': 'your email must needed for communication'
            }
        }

    def clean(self):
        cleaned_data = super(SchoolUserModelForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise ValidationError(
                "password and confirm_password do not match."
            )
        return cleaned_data

    def clean_email(self):
        val_email = self.cleaned_data.get('email')
        return val_email.lower()

    def clean_password(self):
        val_password = self.cleaned_data.get('password')
        if len(val_password) < 8:
            raise ValidationError(
                "Your Password must contain at least 8 characters."
            )
        elif reg(r'\d+', val_password) and reg(r'[a-z]+', val_password) and reg(r'[A-Z]+', val_password) and \
                reg(r'\W+', val_password) and not reg(r'\s+', val_password):
            return val_password
        else:
            raise ValidationError(
                "your password should contain [A-Z], [a-z], [0-9] and one special keyword characters.")

    def clean_terms_conditions(self):
        val_tc = self.cleaned_data.get('terms_conditions')
        if not val_tc:
            raise ValidationError(
                "You Need to Accept our terms and Agreements"
            )
        return val_tc

    def __init__(self, *args, **kwargs):
        super(SchoolUserModelForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs['placeholder'] = field.label


# Login Validation Form
class SchoolUserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               error_messages={'required': "Your username required."})
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               error_messages={'required': "Your Password required."}, )

    def clean_username(self):
        val_username = self.cleaned_data['username']
        if not SchoolUser.objects.filter(username=val_username).exists():
            raise ValidationError(f'Username "{val_username}" is not found in our records.')
        return val_username

    def clean(self):
        val_username = self.cleaned_data.get('username')
        val_password = self.cleaned_data.get('password')
        user = authenticate(username=val_username, password=val_password)
        print("M USER", user)
        if user is not None:
            return user
        if val_username:
            self.add_error('password', "You entered incorrect password.")


class FormChangePassword(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        for field in ('old_password', 'new_password1', 'new_password2'):
            self.fields[field].widget.attrs = {'class': 'form-control'}
        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs['placeholder'] = field.label


class SchoolUserEditForm(SchoolUserModelForm):
    class Meta:
        model = SchoolUser
        fields = ['first_name', 'last_name', 'username', 'user_icon', 'email', 'phone', 'local_address', ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'user_icon': forms.FileInput(attrs={'class': 'user-icon', }),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.NumberInput(attrs={'class': 'form-control'}),
            'local_address': forms.Textarea(attrs={'class': 'form-control', 'cols': 10, 'rows': 2}),

        }

    def clean(self):
        cleaned_data = super(SchoolUserModelForm, self).clean()
        return cleaned_data

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from .forms import SchoolUserModelForm, SchoolUserLoginForm, FormChangePassword, SchoolUserEditForm
from .models import SchoolUser


# Create your views here.
def choose_user(request):
    return render(request, "users/user_choice.html")


def student_registration(request):
    """
    this is Student Registration form method. we are specifying users/registration/student
    URL for students only. SchoolUserModelForm have a Meta class where we re-used
    existing django models. that models automatically converted into input field forms.
    when any new registration hits this method it's Student registration hence we use
    reg.user_type = 'S'. it will add user type 'Student' in the database along with user.
    """
    if request.method == 'POST':
        student_reg_form = SchoolUserModelForm(request.POST, request.FILES)
        print("I AM REQUEST POST++ DATA++", request.POST)

        if student_reg_form.is_valid():
            reg = student_reg_form.save(commit=False)
            print("CLEANED DATA +++", student_reg_form.cleaned_data, end='\n\n')
            reg.user_type = 'S'
            reg.set_password(student_reg_form.cleaned_data.get('password'))
            # Final Save Data to database
            reg.save()
            return redirect('user_submit')

    else:
        student_reg_form = SchoolUserModelForm()
    return render(request, "users/student_register.html", {'form': student_reg_form})


def teacher_registration(request):
    """
    this is Teacher Registration form method. we are specifying users/registration/teacher
    URL for teachers only. SchoolUserModelForm have a Meta class where we re-used
    existing django models. that models automatically converted into input field forms.
    when any new registration hits this method it's Teacher registration hence we use
    reg.user_type = 'T'. it will add user type 'Teacher' in the database along with user.
    """
    if request.method == 'POST':
        teacher_reg_form = SchoolUserModelForm(request.POST, request.FILES)
        if teacher_reg_form.is_valid():
            reg = teacher_reg_form.save(commit=False)
            reg.user_type = 'T'
            reg.set_password(teacher_reg_form.cleaned_data.get('password'))
            # Final Save Data to database
            reg.save()
            return HttpResponseRedirect(reverse('user_submit'))

    else:
        teacher_reg_form = SchoolUserModelForm()
    return render(request, "users/teacher_register.html", {'form': teacher_reg_form})


def thanks_submission(request):
    """
    when any Student or Teacher Successfully registered their profile in our
    website, this method renders a Thank you for your registration HTML template.
    """
    return render(request, 'users/user_success_submit.html')


def users_login(request):
    """
    after succesfully registration for both of the user Student & Teacher, they
    need to Authenticate their self in our website. this method accepts POST
    request when user try to log in & Authenticate himself/herself in this website.
    this method using backend auth to verify user credentials. user must have to verify
    their credentials according to their previous registration credentials.
    """
    if request.method == 'POST':
        user_login_form = SchoolUserLoginForm(request.POST)
        if user_login_form.is_valid():
            user = user_login_form.cleaned_data
            if user:
                login(request, user)
                return redirect('school_dashboard')
        else:
            return render(request, 'users/users_login.html', {'form': user_login_form})
    else:
        if request.user.is_authenticated:
            print("Yes I Am Authenticated")
            # return render(request, 'users/user_already_login.html')
            # Send Him/Her Same Dashboard URL....
            return HttpResponseRedirect(reverse('school_dashboard'))

        else:
            user_login_form = SchoolUserLoginForm()
    return render(request, 'users/users_login.html', {'form': user_login_form})


# User Logout
def log_out(request):
    logout(request)
    return redirect('school_dashboard')


# User Password Reset
def user_change_pass(request):
    """
    this method is for changing user's password, keep in mind that here this
    form inherited Django built-in PasswordChangeForm. this form is not model form.
    it is built-in Django password change from which inherits SetPassword form.
    here SetPassword form directly inherits from (forms.Form).
    """
    if request.user.is_authenticated:
        if request.method == "POST":
            user_pass_change_form = FormChangePassword(user=request.user, data=request.POST)
            if user_pass_change_form.is_valid():
                print("DICT++", user_pass_change_form.__dict__)
                user_pass_change_form.save()
                return HttpResponse("Successfully Changed your password")
        else:
            user_pass_change_form = FormChangePassword(user=request.user)
        return render(request, "users/change_password.html", {'form': user_pass_change_form})
    else:
        return HttpResponseRedirect(reverse('users_login'))


def users_dataset(request):
    context = {"dataset": SchoolUser.objects.all()}
    return render(request, "users/users_dataset.html", context)


def user_detail_data(request, ids):
    SchoolUser.objects.get(id=ids).delete()
    return HttpResponseRedirect(reverse('users_dataset'))


def user_profile_edit(request):
    """
    1 - user can change/update their account information.
    2 - this method verifies SchoolUserEditForm and generated cleaned_data.
    3 - SchoolUserEditForm carrying needful user fields.
    4 - this form inherit SchoolUserModelForm, which is a ModelForm.
    """
    if request.user.is_authenticated:
        if request.method == "POST":
            user_edit_form = SchoolUserEditForm(request.POST, request.FILES, instance=request.user)
            if user_edit_form.is_valid():
                user_edit_form.save()
                messages.success(request, message='profile Updated successfully..')
                # return HttpResponseRedirect(reverse('school_dashboard'))
        else:
            user_edit_form = SchoolUserEditForm(instance=request.user)
    else:
        return HttpResponseRedirect(reverse('users_login'))
    return render(request, "users/user_profile_edit.html", {'user_edit_fm': user_edit_form})

users/templates/users/change_password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--      BOOTSTRAP CSS LINK....-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>Title</title>
    <style>
    .errorlist {
        color: #cc0033;
        font-family: Helvetica, Arial, sans-serif;
        font-weight: bold;
        line-height: 20px;
        text-shadow: 1px 1px rgba(250,250,250,.3);
}







    </style>
</head>
<body>

<form method="post" novalidate>
    {% csrf_token %}
    <div class="form-row">
        {% for field in form %}
        <div class="col-md-9 mb-3">
            {{field.label_tag}} {{field}} <span class="errorlist">{{field.errors|striptags}} </span>
        </div>
        {% endfor %}
    </div>

    <button type="submit" class="btn btn-outline-warning">Set Password</button>
</form>


</body>
</html>

users/templates/users/student_register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--      BOOTSTRAP CSS LINK....-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!--      CUSTOM CSS LINK....-->
    <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
    <title>Student Register</title>
</head>
<body>

<!--    Student Registration Form-->

<form method="POST" enctype="multipart/form-data" novalidate>
    {% csrf_token %}    <!-- Django Cross Site Verification -->
    {% block teacher_reg %}
    <div class="form-row mt-2">
        <div class="col-md-9 mb-3">
            {{form.first_name.label_tag}}
            {{form.first_name}} <span class="errorlist"> {{form.first_name.errors|striptags}} </span>
        </div>
        <div class="col-md-9 mb-3">
            {{form.last_name.label_tag}}
            {{form.last_name}} <span class="errorlist"> {{form.last_name.errors|striptags}} </span>
        </div>
        <div class="col-md-9 mb-3">
            {{form.username.label_tag}}
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupPrepend2">@</span>
                </div>
                {{form.username}}
                <span class="errorlist"> {{form.username.errors|striptags}} </span>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-9 mb-3">
            {{form.email.label_tag}}
            {{form.email}} <span class="errorlist"> {{form.email.errors|striptags}} </span>
        </div>
        <div class="col-md-9 mb-3">
            {{form.user_icon.label_tag}}
            {{form.user_icon}} <span class="errorlist"> {{form.user_icon.errors|striptags}} </span>
        </div>
        <div class="col-md-9 mb-3">
            {{form.standard.label_tag}}
            {{form.standard}} <span class="errorlist"> {{form.standard.errors|striptags}} </span>
        </div>
        <div class="col-md-9 mb-3">
            {{form.password.label_tag}}
            {{form.password}} <span class="errorlist"> {{form.password.errors|striptags}} </span>
        </div>
        <div class="col-md-9 mb-3">
            {{form.confirm_password.label_tag}}
            {{form.confirm_password}} <span class="errorlist">  {{form.non_field_errors|striptags}} </span>

        </div>
    </div>
    {% endblock %}
    <div class="form-group">
        <div class="form-check">
            <label for="id_terms_conditions" class="form-check-label">{{form.terms_conditions.label}}</label>
            {{ form.terms_conditions }} <span class="errorlist m-4"> {{form.terms_conditions.errors|striptags}} </span>
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
    <button class="btn btn-danger" type="reset">Clear Form</button>
    <a href="{% url 'users_login' %}" class="btn btn-outline-success">Go to Login</a>
</form>

<!--    Student Registration Form ENDS ////-->


<!--      CUSTOM JAVASCRIPT LINK....-->
<script src="{% static 'users/js/users.js' %}"></script>
</body>
</html>

users/templates/users/teacher_register.html
{% extends "./student_register.html" %}


{% block teacher_reg %}

<div class="form-row mt-2">
    <div class="col-md-9 mb-3">
        {{form.username.label_tag}}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrepend2">@</span>
            </div>
            {{form.username}}
            <span class="errorlist"> {{form.username.errors|striptags}} </span>
        </div>
    </div>
</div>
<div class="form-row">
    <div class="col-md-9 mb-3">
        {{form.email.label_tag}}
        {{form.email}} <span class="errorlist"> {{form.email.errors|striptags}} </span>
    </div>
    <div class="col-md-9 mb-3">
        {{form.user_icon.label_tag}}
        {{form.user_icon}} <span class="errorlist"> {{form.user_icon.errors|striptags}} </span>
    </div>
    <div class="col-md-9 mb-3">
        {{form.subject.label_tag}}
        {{form.subject}} <span class="errorlist"> {{form.subject.errors|striptags}} </span>
    </div>
    <div class="col-md-9 mb-3">
        {{form.password.label_tag}}
        {{form.password}} <span class="errorlist"> {{form.password.errors|striptags}} </span>
    </div>
    <div class="col-md-9 mb-3">
        {{form.confirm_password.label_tag}}
        {{form.confirm_password}} <span class="errorlist">{{form.confirm_password.errors|striptags}} </span>
        {{form.non_field_errors}}
    </div>
</div>

{% endblock %}

users/templates/users/user_already_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--    Custom CSS - errors.css-->
    <link rel="stylesheet" href="{% static 'users/css/errors.css' %}">
    <title>Already Login</title>
</head>
<body>

<!--ALREADY LOGIN ERROR PAGE-->

<h1>401</h1>
<div class="cloak__wrapper">
    <div class="cloak__container">
        <div class="cloak"></div>
    </div>
</div>
<div class="info">
    <h2>something went wrong</h2>
    <p>it seems you are already logged in. first logout your current session to login again... </p>
    <a href="{% url 'school_dashboard' %}" target="_blank" rel="noreferrer noopener">Back to Dashboard</a>
</div>


</body>
</html>

users/templates/users/user_choice.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <!--      BOOTSTRAP CSS LINK....-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!--    Custom CSS - main.css-->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Registration Type</title>
</head>
<body>
<div class="container">
    <div class="user-choice">
        <h2>Choose Account Type</h2>

        <div class="options">

            <input type="radio" name="option" id="Student">
            <label for="Student">
                <span class="icon__select"><i class="fas fa-user"></i></span>
                <h3 class="user-type">Student</h3>
                <a href="{% url 'student_reg' %}">
                    <span class="selected"><i class="fas fa-check"></i></span>
                </a>

            </label>

            <input type="radio" name="option" id="Teacher">
            <label for="Teacher">
                <span class="icon__select"> <i class="fa-sharp fa-solid fa-person-chalkboard"></i>  </span>
                <h3 class="user-type">Teacher</h3>
                <a href="{% url 'teacher_reg' %}">
                    <span class="selected"><i class="fas fa-check"></i></span>
                </a>
            </label>
        </div>
        <a href="{% url 'users_login' %}" class="btn btn-primary btn-lg btn-block"> Already User? Login </a>

    </div>
</div>
<!-- font awesome -->
<script src="https://kit.fontawesome.com/8294e1c522.js" crossorigin="anonymous"></script>
<script src="main.js"></script>
</body>
</html>

users/templates/users/user_detail_data.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>User Detail Data</title>
</head>
<body>

<div class="main">

  <!-- Specify fields to be displayed -->
  {{ data.username }}<br/>
  {{ data.email }}<br/>

</div>

</body>
</html>

users/templates/users/user_profile_edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- bootstrap css file link  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!--      CUSTOM CSS LINK....-->
    <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
    <title>User Profile Edit</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class=" {{ message.tags }} "> {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                {% if request.user.user_icon %}
                <img class="rounded-circle mt-5 pf-dp" src="{{ request.user.user_icon.url }}"/>
                {% else %}
                <img class="rounded-circle mt-5 pf-dp" src="" alt="No Profile Picture"/>
                {% endif %}
                <span class="font-weight-bold">{{request.user.first_name}}</span>
                <span class="text-black-50">{{request.user.username}} </span>
            </div>
        </div>

        <div class="col-md-5 border-right">
            <form class="p-3 py-5" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <label for="id_user_icon" class="user-icon-label"><i class='fas fa-pencil-alt'
                                                                         style='font-size:19px; color: #0190b0;'></i></label>
                    {{ user_edit_fm.user_icon }}
                </div>
                <div class="d-flex justify-content-between align-items-center mb-3"><h4 class="text-right">Profile
                    Settings</h4></div>
                <div class="row mt-2">
                    <div class="col-md-6">
                        {{ user_edit_fm.first_name.label_tag}}
                        {{ user_edit_fm.first_name }}
                    </div>
                    <div class="col-md-6">
                        {{ user_edit_fm.last_name.label_tag}}
                        {{ user_edit_fm.last_name }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12">
                        {{ user_edit_fm.phone.label_tag }}
                        {{ user_edit_fm.phone }}
                    </div>
                    <div class="col-md-12 mt-2">
                        {{ user_edit_fm.local_address.label_tag }}
                        {{ user_edit_fm.local_address }}
                    </div>
                    <div class="col-md-12 mt-2">
                        {{ user_edit_fm.username.label_tag }}
                        {{ user_edit_fm.username }}
                    </div>
                    <div class="col-md-12 mt-2">
                        {{ user_edit_fm.email.label_tag }}
                        {{ user_edit_fm.email }}
                    </div>
                    <div class="col-md-12 mt-4">
                        <a href="{% url 'user_change_pass' %}">Change Password</a>
                    </div>
                </div>

                <div class="mt-5 text-center">
                    <button class="btn btn-outline-warning profile-button" type="submit">Update Profile</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- font awesome -->
<script src="https://kit.fontawesome.com/8294e1c522.js" crossorigin="anonymous"></script>
<!-- bootstrap js file link  -->
<script src="{% static 'js/bootstrap.js' %}"></script>

</body>
</html>

users/templates/users/user_success_submit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--    Bootstrap CSS Linked-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>Success Register</title>
    <style>
        .submit-box {
             display: flex;
             flex-direction: row;
             justify-content: center;
        }

    </style>
</head>
<body>
<div class="submit-box">
    <img class="submit-img" src="{% static 'users/images/submit-img.png' %}" alt="Submitting Message">
</div>
<div class="text-center">
    <a href="{% url 'users_login' %}" class="btn btn-primary">Login Now</a>
</div>
</body>
</html>

users/templates/users/users_dataset.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--      BOOTSTRAP CSS LINK....-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>Users Dataset</title>
</head>
<body>
<section class="vh-100" style="background-color: #eee;">
    <div class="container py-3 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-7">
                <div class="card rounded-3">
                    <div class="card-body p-4">
                        <h4 class="text-center my-3 pb-3">To Do App</h4>

                        <table class="table mb-4">
                            <thead>
                            <tr>
                                <th scope="col">No.</th>
                                <th scope="col">User Email</th>
                                <th scope="col">Status</th>
                                <th scope="col">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for data in dataset %}
                            {{data.id}}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td> {{ data.email }}</td>
                                <td>In progress</td>
                                <td>
                                    <a href="{% url 'user_detail_data' data.id  %}">
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </a>
                                    <button type="submit" class="btn btn-success ms-1">Update</button>
                                </td>
                            </tr>
                            {% endfor %}

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


</body>
</html>